/**
 * Generated from the approved UND 90-day tracker.
 * Source: UND_90일_팀트래커.html
 * Do not edit this file by hand; run scripts/generate-und-tracker-plan.mjs.
 */
var MH_UND_TRACKER_PLAN = [
  {
    "id": "P0-MKT-1",
    "team": "MKT",
    "phase": "P0",
    "title": "킥오프 실시 · 플랫폼 서면 확정 수령 (카페24 유지 권고)",
    "category": "플랫폼 확정",
    "week": 1,
    "planNote": "",
    "sortOrder": 1
  },
  {
    "id": "P0-MKT-2",
    "team": "MKT",
    "phase": "P0",
    "title": "계정 권한 7종 인수 (GA4·GSC·서치어드바이저·카페24·스마트스토어·유튜브·메타)",
    "category": "계정 권한",
    "week": 1,
    "planNote": "갑 명의 개설 · 관리자 권한 상시 보유",
    "sortOrder": 2
  },
  {
    "id": "P0-MKT-3",
    "team": "MKT",
    "phase": "P0",
    "title": "Screaming Frog 전수 크롤 — 색인·캐노니컬·렌더링 진단",
    "category": "기술 점검",
    "week": 1,
    "planNote": "",
    "sortOrder": 3
  },
  {
    "id": "P0-MKT-4",
    "team": "MKT",
    "phase": "P0",
    "title": "GA4 전환 이벤트 설치 및 발화 검증 (구매·상담·예약·톡톡)",
    "category": "전환 추적",
    "week": 2,
    "planNote": "",
    "sortOrder": 4
  },
  {
    "id": "P0-MKT-5",
    "team": "MKT",
    "phase": "P0",
    "title": "UTM 4단 명명 규칙 확정 및 서면 승인",
    "category": "유입 경로 추적",
    "week": 2,
    "planNote": "",
    "sortOrder": 5
  },
  {
    "id": "P0-MKT-6",
    "team": "MKT",
    "phase": "P0",
    "title": "XML 사이트맵 생성 → robots.txt 등재 → GSC·서치어드바이저 제출",
    "category": "검색 색인",
    "week": 2,
    "planNote": "",
    "sortOrder": 6
  },
  {
    "id": "P0-MKT-7",
    "team": "MKT",
    "phase": "P0",
    "title": "카테고리별 고유 meta description + 상단 카피 작성",
    "category": "카테고리 문구",
    "week": 2,
    "planNote": "",
    "sortOrder": 7
  },
  {
    "id": "P0-MKT-8",
    "team": "MKT",
    "phase": "P0",
    "title": "상품 네이밍 규칙 통일안 작성 및 갑 승인",
    "category": "상품명 정리",
    "week": 1,
    "planNote": "",
    "sortOrder": 8
  },
  {
    "id": "P0-MKT-9",
    "team": "MKT",
    "phase": "P0",
    "title": "브랜드 메시지 체계 · 핵심 키워드 맵 · 페르소나 정의",
    "category": "구축 산출물",
    "week": 1,
    "planNote": "별첨6-4 구축 검수 대상 · 미인도 시 검수 불가",
    "sortOrder": 9
  },
  {
    "id": "P0-MKT-10",
    "team": "MKT",
    "phase": "P0",
    "title": "키워드 SERP 판정 (진입/Stop) · 키워드 마스터 시트",
    "category": "키워드 선정",
    "week": 1,
    "planNote": "",
    "sortOrder": 10
  },
  {
    "id": "P0-MKT-11",
    "team": "MKT",
    "phase": "P0",
    "title": "판매·광고 채널 6종 개설 및 갑 명의 세팅",
    "category": "구축 산출물",
    "week": 1,
    "planNote": "별첨6-4 구축 검수 대상 · 미인도 시 검수 불가",
    "sortOrder": 11
  },
  {
    "id": "P0-MKT-12",
    "team": "MKT",
    "phase": "P0",
    "title": "광고 계정 세팅 · 브랜드 키워드 방어 소재 입고",
    "category": "채널 운영",
    "week": 2,
    "planNote": "",
    "sortOrder": 12
  },
  {
    "id": "P0-MKT-13",
    "team": "MKT",
    "phase": "P0",
    "title": "네이버 블로그 10건 발행 (구축기)",
    "category": "네이버 채널",
    "week": 3,
    "planNote": "",
    "sortOrder": 13
  },
  {
    "id": "P0-MKT-14",
    "team": "MKT",
    "phase": "P0",
    "title": "스마트플레이스 최적화 — 남양주 (사진·소식·길찾기·후기)",
    "category": "네이버 채널",
    "week": 1,
    "planNote": "",
    "sortOrder": 14
  },
  {
    "id": "P0-MKT-15",
    "team": "MKT",
    "phase": "P0",
    "title": "브랜드 표기 변형 키워드 매핑 (유엔디·UND·유앤디)",
    "category": "브랜드 검색",
    "week": 1,
    "planNote": "",
    "sortOrder": 15
  },
  {
    "id": "P0-MKT-16",
    "team": "MKT",
    "phase": "P0",
    "title": "코스트코 경유 키워드 SERP 판정 및 진입 확정",
    "category": "키워드 선정",
    "week": 1,
    "planNote": "",
    "sortOrder": 16
  },
  {
    "id": "P0-MKT-17",
    "team": "MKT",
    "phase": "P0",
    "title": "오픈마켓 무단 등록 전수 조사 및 목록화",
    "category": "채널 정리",
    "week": 1,
    "planNote": "",
    "sortOrder": 17
  },
  {
    "id": "P0-MKT-18",
    "team": "MKT",
    "phase": "P0",
    "title": "상담 기록 시트 설계 — 유입 경로 필수 항목",
    "category": "상담 데이터",
    "week": 1,
    "planNote": "",
    "sortOrder": 18
  },
  {
    "id": "P0-MKT-19",
    "team": "MKT",
    "phase": "P0",
    "title": "n8n 최소 구성 가동 (감지·초안·승인·배포)",
    "category": "제작 자동화",
    "week": 3,
    "planNote": "",
    "sortOrder": 19
  },
  {
    "id": "P0-MKT-20",
    "team": "MKT",
    "phase": "P0",
    "title": "Looker Studio 대시보드 v1 구축",
    "category": "대시보드",
    "week": 3,
    "planNote": "",
    "sortOrder": 20
  },
  {
    "id": "P0-MKT-21",
    "team": "MKT",
    "phase": "P0",
    "title": "채널별 가격·모델명 정합성 확인 (코스트코·SSG·자사몰)",
    "category": "채널 정합성",
    "week": 1,
    "planNote": "",
    "sortOrder": 21
  },
  {
    "id": "P0-MKT-22",
    "team": "MKT",
    "phase": "P0",
    "title": "8/31 촬영·콘텐츠 리스트 + 90일 일정 가안 전달",
    "category": "미팅 준비",
    "week": 1,
    "planNote": "9/2 확정 미팅의 전제 산출물",
    "sortOrder": 22
  },
  {
    "id": "P0-MKT-23",
    "team": "MKT",
    "phase": "P0",
    "title": "9/2 컨셉·일정 확정 미팅 실시 · 결정사항 서면화",
    "category": "미팅 준비",
    "week": 1,
    "planNote": "",
    "sortOrder": 23
  },
  {
    "id": "P0-MKT-24",
    "team": "MKT",
    "phase": "P0",
    "title": "갑 확인 요청 9건 회신 수령 및 계획 반영",
    "category": "갑 확인",
    "week": 1,
    "planNote": "미회신 시 후속 과업 착수 불가 — 지연 귀책 소명 근거",
    "sortOrder": 24
  },
  {
    "id": "P0-MKT-25",
    "team": "MKT",
    "phase": "P0",
    "title": "경쟁 3사 모니터링 시트 구축 (검색 순위·후기 수·광고 집행)",
    "category": "경쟁 모니터링",
    "week": 2,
    "planNote": "",
    "sortOrder": 25
  },
  {
    "id": "P0-MKT-26",
    "team": "MKT",
    "phase": "P0",
    "title": "현행과 다른 과거 유통 이력 검색 오정보 정리 범위 확정·조치",
    "category": "채널 정리",
    "week": 2,
    "planNote": "",
    "sortOrder": 26
  },
  {
    "id": "P0-MKT-27",
    "team": "MKT",
    "phase": "P0",
    "title": "투자 연계 지원사업 2~3개 큐레이션 및 제출 가이드 제공",
    "category": "지원사업",
    "week": 3,
    "planNote": "별첨5 사전 서면 승인 대상 여부 확인",
    "sortOrder": 27
  },
  {
    "id": "P0-MKT-28",
    "team": "MKT",
    "phase": "P0",
    "title": "12월 코스트코 행사 역산 일정표 작성 (선제작 리드타임 반영)",
    "category": "행사 대비",
    "week": 3,
    "planNote": "",
    "sortOrder": 28
  },
  {
    "id": "P0-DSN-1",
    "team": "DSN",
    "phase": "P0",
    "title": "테마 커스터마이징 · 디자인 시안 확정 (무상 수정 2회 이내)",
    "category": "디자인 시안",
    "week": 1,
    "planNote": "",
    "sortOrder": 29
  },
  {
    "id": "P0-DSN-2",
    "team": "DSN",
    "phase": "P0",
    "title": "자사몰 브랜드 페이지 8종 제작·배포 (메인 1 + 서브 7)",
    "category": "브랜드 페이지",
    "week": 2,
    "planNote": "",
    "sortOrder": 30
  },
  {
    "id": "P0-DSN-3",
    "team": "DSN",
    "phase": "P0",
    "title": "제품 상세페이지 5종 기획·디자인·등록",
    "category": "커머스 세팅",
    "week": 3,
    "planNote": "",
    "sortOrder": 31
  },
  {
    "id": "P0-DSN-4",
    "team": "DSN",
    "phase": "P0",
    "title": "SEO 단일 스크롤 랜딩페이지 1식 배포",
    "category": "구축 산출물",
    "week": 3,
    "planNote": "별첨6-4 구축 검수 대상 · 미인도 시 검수 불가",
    "sortOrder": 32
  },
  {
    "id": "P0-DSN-5",
    "team": "DSN",
    "phase": "P0",
    "title": "커머스 시스템 UI · 주문제작 옵션 구조 반영",
    "category": "커머스 세팅",
    "week": 2,
    "planNote": "",
    "sortOrder": 33
  },
  {
    "id": "P0-DSN-6",
    "team": "DSN",
    "phase": "P0",
    "title": "쇼룸 방문 예약 폼·지도·동선 구축 (서브4)",
    "category": "쇼룸 예약 동선",
    "week": 2,
    "planNote": "",
    "sortOrder": 34
  },
  {
    "id": "P0-DSN-7",
    "team": "DSN",
    "phase": "P0",
    "title": "리뷰 카운트·평점 리스트 노출 세팅",
    "category": "구매후기",
    "week": 3,
    "planNote": "",
    "sortOrder": 35
  },
  {
    "id": "P0-DSN-8",
    "team": "DSN",
    "phase": "P0",
    "title": "인스타그램 카드뉴스 10건 (초기 콘텐츠)",
    "category": "구축 산출물",
    "week": 3,
    "planNote": "별첨6-4 구축 검수 대상 · 미인도 시 검수 불가",
    "sortOrder": 36
  },
  {
    "id": "P0-DSN-9",
    "team": "DSN",
    "phase": "P0",
    "title": "유튜브 롱폼 썸네일 2종",
    "category": "구축 산출물",
    "week": 3,
    "planNote": "별첨6-4 구축 검수 대상 · 미인도 시 검수 불가",
    "sortOrder": 37
  },
  {
    "id": "P0-DSN-10",
    "team": "DSN",
    "phase": "P0",
    "title": "후기 요청 메시지·카드 템플릿 제작",
    "category": "구매후기",
    "week": 3,
    "planNote": "",
    "sortOrder": 38
  },
  {
    "id": "P0-DSN-11",
    "team": "DSN",
    "phase": "P0",
    "title": "자사몰 운영 매뉴얼 제작 (갑 자체 운영용)",
    "category": "운영 매뉴얼",
    "week": 3,
    "planNote": "",
    "sortOrder": 39
  },
  {
    "id": "P0-DSN-12",
    "team": "DSN",
    "phase": "P0",
    "title": "IR 자료 보강 — 투자 하이라이트 서머리 · 마케팅/사업화 전략 페이지",
    "category": "IR 지원",
    "week": 1,
    "planNote": "별첨5 범위 외 작업 여부 사전 확인",
    "sortOrder": 40
  },
  {
    "id": "P0-DSN-13",
    "team": "DSN",
    "phase": "P0",
    "title": "배송 후기 요청 카드 · 상담 종료 시점 평점 요청 스크립트 제작",
    "category": "구매후기",
    "week": 3,
    "planNote": "",
    "sortOrder": 41
  },
  {
    "id": "P0-DSN-14",
    "team": "DSN",
    "phase": "P0",
    "title": "상세페이지 상위 라인 비교 동선 설계 (코스트코 유입 업셀 경로)",
    "category": "커머스 세팅",
    "week": 2,
    "planNote": "",
    "sortOrder": 42
  },
  {
    "id": "P0-VID-1",
    "team": "VID",
    "phase": "P0",
    "title": "촬영 기획 · 시나리오 · 콘티 · 컷리스트 작성",
    "category": "촬영",
    "week": 1,
    "planNote": "",
    "sortOrder": 43
  },
  {
    "id": "P0-VID-2",
    "team": "VID",
    "phase": "P0",
    "title": "촬영 D-5 체크리스트 갑 서면 확인",
    "category": "촬영 사전 확정",
    "week": 1,
    "planNote": "D-5 서면 확인 · 미확인 시 촬영 연기 사유",
    "sortOrder": 44
  },
  {
    "id": "P0-VID-3",
    "team": "VID",
    "phase": "P0",
    "title": "촬영 1회차 실행 (8시간)",
    "category": "구축 산출물",
    "week": 2,
    "planNote": "별첨6-4 구축 검수 대상 · 미인도 시 검수 불가",
    "sortOrder": 45
  },
  {
    "id": "P0-VID-4",
    "team": "VID",
    "phase": "P0",
    "title": "촬영 2회차 실행 (8시간)",
    "category": "구축 산출물",
    "week": 3,
    "planNote": "별첨6-4 구축 검수 대상 · 미인도 시 검수 불가",
    "sortOrder": 46
  },
  {
    "id": "P0-VID-5",
    "team": "VID",
    "phase": "P0",
    "title": "제품 컷 · 상세페이지용 스틸 촬영",
    "category": "촬영",
    "week": 2,
    "planNote": "",
    "sortOrder": 47
  },
  {
    "id": "P0-VID-6",
    "team": "VID",
    "phase": "P0",
    "title": "가죽 종 비교 촬영 — 자체 소재로 카우/버팔로 대조",
    "category": "가죽 콘텐츠",
    "week": 2,
    "planNote": "",
    "sortOrder": 48
  },
  {
    "id": "P0-VID-7",
    "team": "VID",
    "phase": "P0",
    "title": "원부자재 추적 체계 공정 촬영",
    "category": "추적 콘텐츠",
    "week": 2,
    "planNote": "",
    "sortOrder": 49
  },
  {
    "id": "P0-VID-8",
    "team": "VID",
    "phase": "P0",
    "title": "인플루언서 섭외 및 조건 서면 승인",
    "category": "인플루언서",
    "week": 2,
    "planNote": "",
    "sortOrder": 50
  },
  {
    "id": "P0-VID-9",
    "team": "VID",
    "phase": "P0",
    "title": "CEO 인용구 3~5개 수집 (GEO 블록쿼트 뱅크)",
    "category": "인용구 수집",
    "week": 2,
    "planNote": "",
    "sortOrder": 51
  },
  {
    "id": "P0-VID-10",
    "team": "VID",
    "phase": "P0",
    "title": "유튜브 롱폼 2편 편집·업로드",
    "category": "구축 산출물",
    "week": 3,
    "planNote": "별첨6-4 구축 검수 대상 · 미인도 시 검수 불가",
    "sortOrder": 52
  },
  {
    "id": "P0-VID-11",
    "team": "VID",
    "phase": "P0",
    "title": "유튜브 숏폼 10편 편집·업로드",
    "category": "구축 산출물",
    "week": 3,
    "planNote": "별첨6-4 구축 검수 대상 · 미인도 시 검수 불가",
    "sortOrder": 53
  },
  {
    "id": "P0-VID-12",
    "team": "VID",
    "phase": "P0",
    "title": "유튜브 채널 SEO 세팅 (제목·설명·태그·챕터·재생목록)",
    "category": "채널 운영",
    "week": 3,
    "planNote": "",
    "sortOrder": 54
  },
  {
    "id": "P0-VID-13",
    "team": "VID",
    "phase": "P0",
    "title": "촬영 원본 아카이브 구축 및 보관",
    "category": "원본 보관",
    "week": 3,
    "planNote": "",
    "sortOrder": 55
  },
  {
    "id": "P0-VID-14",
    "team": "VID",
    "phase": "P0",
    "title": "코스트코 감사 결과 문서 수령 후 대외 표현 가능 범위 확정",
    "category": "추적 콘텐츠",
    "week": 2,
    "planNote": "미확보 시 '국내 유일'·'최초' 표현 사용 금지 — 표시광고법 리스크",
    "sortOrder": 56
  },
  {
    "id": "P0-VID-15",
    "team": "VID",
    "phase": "P0",
    "title": "가죽 비교 컷 자체 촬영 원칙 확인 (외부 커뮤니티 캡처 미사용)",
    "category": "가죽 콘텐츠",
    "week": 2,
    "planNote": "저작권·비방광고 리스크 차단 조건",
    "sortOrder": 57
  },
  {
    "id": "M1-MKT-1",
    "team": "MKT",
    "phase": "M1",
    "title": "기초 데이터 A등급 실측 (운영 개시 +5영업일)",
    "category": "기준 데이터",
    "week": 1,
    "planNote": "운영 개시 +5영업일 실측 · 전 KPI 산정의 기준선",
    "sortOrder": 58
  },
  {
    "id": "M1-MKT-2",
    "team": "MKT",
    "phase": "M1",
    "title": "핵심 성과목표 서면 확정 (+10영업일 · 가중치·산식·출처)",
    "category": "목표 합의",
    "week": 2,
    "planNote": "제19조② 운영 개시 +10영업일 서면 확정",
    "sortOrder": 59
  },
  {
    "id": "M1-MKT-3",
    "team": "MKT",
    "phase": "M1",
    "title": "주 1회 진행 공유 개시 (최초 1개월)",
    "category": "주간 공유",
    "week": 1,
    "planNote": "최초 1개월 주 1회 진행 공유 의무",
    "sortOrder": 60
  },
  {
    "id": "M1-MKT-4",
    "team": "MKT",
    "phase": "M1",
    "title": "콘텐츠 캘린더 제안 및 갑 승인 수령",
    "category": "콘텐츠 캘린더",
    "week": 1,
    "planNote": "",
    "sortOrder": 61
  },
  {
    "id": "M1-MKT-5",
    "team": "MKT",
    "phase": "M1",
    "title": "네이버 블로그 4건 발행 (주제축 고정)",
    "category": "월 정량 산출물",
    "week": 4,
    "planNote": "별첨3 · 제20조① 수량 미달 시 이월 또는 환산단가 차감",
    "sortOrder": 62
  },
  {
    "id": "M1-MKT-6",
    "team": "MKT",
    "phase": "M1",
    "title": "스마트스토어 콘텐츠 3건",
    "category": "네이버 채널",
    "week": 2,
    "planNote": "",
    "sortOrder": 63
  },
  {
    "id": "M1-MKT-7",
    "team": "MKT",
    "phase": "M1",
    "title": "스마트플레이스 갱신 — 남양주 중심",
    "category": "네이버 채널",
    "week": 2,
    "planNote": "",
    "sortOrder": 64
  },
  {
    "id": "M1-MKT-8",
    "team": "MKT",
    "phase": "M1",
    "title": "자사몰 상품 등록·수정 3건",
    "category": "자사몰 운영",
    "week": 4,
    "planNote": "",
    "sortOrder": 65
  },
  {
    "id": "M1-MKT-9",
    "team": "MKT",
    "phase": "M1",
    "title": "광고 주간 최적화 4주 (키워드·입찰·소재·전환 동선)",
    "category": "광고 최적화",
    "week": 4,
    "planNote": "",
    "sortOrder": 66
  },
  {
    "id": "M1-MKT-10",
    "team": "MKT",
    "phase": "M1",
    "title": "댓글·DM 1차 응대 (영업일 24시간 내)",
    "category": "채널 운영",
    "week": 4,
    "planNote": "",
    "sortOrder": 67
  },
  {
    "id": "M1-MKT-11",
    "team": "MKT",
    "phase": "M1",
    "title": "광고 매체별 실집행 증빙 수집",
    "category": "광고 증빙",
    "week": 4,
    "planNote": "제11조③ 집행 증빙 첨부 의무 · 무단 집행 즉시 해지",
    "sortOrder": 68
  },
  {
    "id": "M1-MKT-12",
    "team": "MKT",
    "phase": "M1",
    "title": "주간 브리핑 4회 발송 (한 일·집행·지표·계획)",
    "category": "주간 브리핑",
    "week": 4,
    "planNote": "제30조④ 보고 의무 불이행 시 해지 사유",
    "sortOrder": 69
  },
  {
    "id": "M1-MKT-13",
    "team": "MKT",
    "phase": "M1",
    "title": "상담 시트 유입 경로 집계 및 리포트 반영",
    "category": "상담 데이터",
    "week": 4,
    "planNote": "",
    "sortOrder": 70
  },
  {
    "id": "M1-MKT-14",
    "team": "MKT",
    "phase": "M1",
    "title": "브랜드·지역 검색 순위 점검",
    "category": "브랜드 검색",
    "week": 3,
    "planNote": "",
    "sortOrder": 71
  },
  {
    "id": "M1-MKT-15",
    "team": "MKT",
    "phase": "M1",
    "title": "지원사업 트랙 캘린더·증빙자산 매핑 갱신",
    "category": "지원사업",
    "week": 3,
    "planNote": "",
    "sortOrder": 72
  },
  {
    "id": "M1-MKT-16",
    "team": "MKT",
    "phase": "M1",
    "title": "월간 성과보고서 제출 (익월 5영업일 이내)",
    "category": "월간 보고",
    "week": 5,
    "planNote": "제19조⑧ 보고서 미제출 시 대금 지급 보류",
    "sortOrder": 73
  },
  {
    "id": "M1-MKT-17",
    "team": "MKT",
    "phase": "M1",
    "title": "성과 검토회의 30분 이상 실시",
    "category": "검토회의",
    "week": 5,
    "planNote": "월 1회 30분 이상 실시 의무",
    "sortOrder": 74
  },
  {
    "id": "M1-MKT-A",
    "team": "MKT",
    "phase": "M1",
    "title": "경쟁 3사 검색 순위·후기 수 월간 추적 및 리포트 반영",
    "category": "경쟁 모니터링",
    "week": 3,
    "planNote": "",
    "sortOrder": 75
  },
  {
    "id": "M1-MKT-B",
    "team": "MKT",
    "phase": "M1",
    "title": "쇼룸 주간 응대 캐파 대비 예약 분산 점검",
    "category": "쇼룸 예약 동선",
    "week": 4,
    "planNote": "",
    "sortOrder": 76
  },
  {
    "id": "M1-DSN-1",
    "team": "DSN",
    "phase": "M1",
    "title": "인스타그램 피드 10건 (카드뉴스 포함)",
    "category": "월 정량 산출물",
    "week": 4,
    "planNote": "별첨3 · 제20조① 수량 미달 시 이월 또는 환산단가 차감",
    "sortOrder": 77
  },
  {
    "id": "M1-DSN-2",
    "team": "DSN",
    "phase": "M1",
    "title": "기획전·프로모션 배너 1건",
    "category": "자사몰 운영",
    "week": 4,
    "planNote": "",
    "sortOrder": 78
  },
  {
    "id": "M1-DSN-3",
    "team": "DSN",
    "phase": "M1",
    "title": "유튜브 롱폼 썸네일 2종",
    "category": "촬영",
    "week": 2,
    "planNote": "",
    "sortOrder": 79
  },
  {
    "id": "M1-DSN-4",
    "team": "DSN",
    "phase": "M1",
    "title": "상품 상세 이미지 갱신·보완",
    "category": "자사몰 운영",
    "week": 4,
    "planNote": "",
    "sortOrder": 80
  },
  {
    "id": "M1-DSN-5",
    "team": "DSN",
    "phase": "M1",
    "title": "후기 요청 발송물 제작·갱신",
    "category": "구매후기",
    "week": 4,
    "planNote": "",
    "sortOrder": 81
  },
  {
    "id": "M1-DSN-6",
    "team": "DSN",
    "phase": "M1",
    "title": "자사몰 경미 수정 (월 3시간 이내 관리)",
    "category": "자사몰 수정",
    "week": 4,
    "planNote": "",
    "sortOrder": 82
  },
  {
    "id": "M1-DSN-A",
    "team": "DSN",
    "phase": "M1",
    "title": "후기 요청 실행 결과 점검 및 스크립트 보완",
    "category": "구매후기",
    "week": 4,
    "planNote": "",
    "sortOrder": 83
  },
  {
    "id": "M1-VID-1",
    "team": "VID",
    "phase": "M1",
    "title": "촬영 D-5 체크리스트 갑 서면 확인",
    "category": "촬영 사전 확정",
    "week": 1,
    "planNote": "D-5 서면 확인 · 미확인 시 촬영 연기 사유",
    "sortOrder": 84
  },
  {
    "id": "M1-VID-2",
    "team": "VID",
    "phase": "M1",
    "title": "촬영 1회 실행 (8시간)",
    "category": "촬영",
    "week": 2,
    "planNote": "",
    "sortOrder": 85
  },
  {
    "id": "M1-VID-3",
    "team": "VID",
    "phase": "M1",
    "title": "유튜브 롱폼 2편 제작·게시",
    "category": "월 정량 산출물",
    "week": 4,
    "planNote": "별첨3 · 제20조① 수량 미달 시 이월 또는 환산단가 차감",
    "sortOrder": 86
  },
  {
    "id": "M1-VID-4",
    "team": "VID",
    "phase": "M1",
    "title": "유튜브 숏폼 10편 제작·게시 (릴스 크로스 배포)",
    "category": "월 정량 산출물",
    "week": 4,
    "planNote": "별첨3 · 제20조① 수량 미달 시 이월 또는 환산단가 차감",
    "sortOrder": 87
  },
  {
    "id": "M1-VID-5",
    "team": "VID",
    "phase": "M1",
    "title": "익월분 선행 제작 버퍼 확보",
    "category": "선행 제작",
    "week": 4,
    "planNote": "",
    "sortOrder": 88
  },
  {
    "id": "M2-MKT-1",
    "team": "MKT",
    "phase": "M2",
    "title": "콘텐츠 캘린더 제안 및 갑 승인 수령",
    "category": "콘텐츠 캘린더",
    "week": 1,
    "planNote": "",
    "sortOrder": 89
  },
  {
    "id": "M2-MKT-2",
    "team": "MKT",
    "phase": "M2",
    "title": "네이버 블로그 4건 발행 (주제축 고정)",
    "category": "월 정량 산출물",
    "week": 4,
    "planNote": "별첨3 · 제20조① 수량 미달 시 이월 또는 환산단가 차감",
    "sortOrder": 90
  },
  {
    "id": "M2-MKT-3",
    "team": "MKT",
    "phase": "M2",
    "title": "스마트스토어 콘텐츠 3건",
    "category": "네이버 채널",
    "week": 2,
    "planNote": "",
    "sortOrder": 91
  },
  {
    "id": "M2-MKT-4",
    "team": "MKT",
    "phase": "M2",
    "title": "스마트플레이스 갱신 — 남양주 중심",
    "category": "네이버 채널",
    "week": 2,
    "planNote": "",
    "sortOrder": 92
  },
  {
    "id": "M2-MKT-5",
    "team": "MKT",
    "phase": "M2",
    "title": "자사몰 상품 등록·수정 3건",
    "category": "자사몰 운영",
    "week": 4,
    "planNote": "",
    "sortOrder": 93
  },
  {
    "id": "M2-MKT-6",
    "team": "MKT",
    "phase": "M2",
    "title": "광고 주간 최적화 4주 (키워드·입찰·소재·전환 동선)",
    "category": "광고 최적화",
    "week": 4,
    "planNote": "",
    "sortOrder": 94
  },
  {
    "id": "M2-MKT-7",
    "team": "MKT",
    "phase": "M2",
    "title": "댓글·DM 1차 응대 (영업일 24시간 내)",
    "category": "채널 운영",
    "week": 4,
    "planNote": "",
    "sortOrder": 95
  },
  {
    "id": "M2-MKT-8",
    "team": "MKT",
    "phase": "M2",
    "title": "광고 매체별 실집행 증빙 수집",
    "category": "광고 증빙",
    "week": 4,
    "planNote": "제11조③ 집행 증빙 첨부 의무 · 무단 집행 즉시 해지",
    "sortOrder": 96
  },
  {
    "id": "M2-MKT-9",
    "team": "MKT",
    "phase": "M2",
    "title": "주간 브리핑 4회 발송 (한 일·집행·지표·계획)",
    "category": "주간 브리핑",
    "week": 4,
    "planNote": "제30조④ 보고 의무 불이행 시 해지 사유",
    "sortOrder": 97
  },
  {
    "id": "M2-MKT-10",
    "team": "MKT",
    "phase": "M2",
    "title": "상담 시트 유입 경로 집계 및 리포트 반영",
    "category": "상담 데이터",
    "week": 4,
    "planNote": "",
    "sortOrder": 98
  },
  {
    "id": "M2-MKT-11",
    "team": "MKT",
    "phase": "M2",
    "title": "브랜드·지역 검색 순위 점검",
    "category": "브랜드 검색",
    "week": 3,
    "planNote": "",
    "sortOrder": 99
  },
  {
    "id": "M2-MKT-12",
    "team": "MKT",
    "phase": "M2",
    "title": "지원사업 트랙 캘린더·증빙자산 매핑 갱신",
    "category": "지원사업",
    "week": 3,
    "planNote": "",
    "sortOrder": 100
  },
  {
    "id": "M2-MKT-13",
    "team": "MKT",
    "phase": "M2",
    "title": "월간 성과보고서 제출 (익월 5영업일 이내)",
    "category": "월간 보고",
    "week": 5,
    "planNote": "제19조⑧ 보고서 미제출 시 대금 지급 보류",
    "sortOrder": 101
  },
  {
    "id": "M2-MKT-14",
    "team": "MKT",
    "phase": "M2",
    "title": "성과 검토회의 30분 이상 실시",
    "category": "검토회의",
    "week": 5,
    "planNote": "월 1회 30분 이상 실시 의무",
    "sortOrder": 102
  },
  {
    "id": "M2-MKT-A",
    "team": "MKT",
    "phase": "M2",
    "title": "경쟁 3사 검색 순위·후기 수 월간 추적 및 리포트 반영",
    "category": "경쟁 모니터링",
    "week": 3,
    "planNote": "",
    "sortOrder": 103
  },
  {
    "id": "M2-MKT-B",
    "team": "MKT",
    "phase": "M2",
    "title": "쇼룸 주간 응대 캐파 대비 예약 분산 점검",
    "category": "쇼룸 예약 동선",
    "week": 4,
    "planNote": "",
    "sortOrder": 104
  },
  {
    "id": "M2-DSN-1",
    "team": "DSN",
    "phase": "M2",
    "title": "인스타그램 피드 10건 (카드뉴스 포함)",
    "category": "월 정량 산출물",
    "week": 4,
    "planNote": "별첨3 · 제20조① 수량 미달 시 이월 또는 환산단가 차감",
    "sortOrder": 105
  },
  {
    "id": "M2-DSN-2",
    "team": "DSN",
    "phase": "M2",
    "title": "기획전·프로모션 배너 1건",
    "category": "자사몰 운영",
    "week": 4,
    "planNote": "",
    "sortOrder": 106
  },
  {
    "id": "M2-DSN-3",
    "team": "DSN",
    "phase": "M2",
    "title": "유튜브 롱폼 썸네일 2종",
    "category": "촬영",
    "week": 2,
    "planNote": "",
    "sortOrder": 107
  },
  {
    "id": "M2-DSN-4",
    "team": "DSN",
    "phase": "M2",
    "title": "상품 상세 이미지 갱신·보완",
    "category": "자사몰 운영",
    "week": 4,
    "planNote": "",
    "sortOrder": 108
  },
  {
    "id": "M2-DSN-5",
    "team": "DSN",
    "phase": "M2",
    "title": "후기 요청 발송물 제작·갱신",
    "category": "구매후기",
    "week": 4,
    "planNote": "",
    "sortOrder": 109
  },
  {
    "id": "M2-DSN-6",
    "team": "DSN",
    "phase": "M2",
    "title": "자사몰 경미 수정 (월 3시간 이내 관리)",
    "category": "자사몰 수정",
    "week": 4,
    "planNote": "",
    "sortOrder": 110
  },
  {
    "id": "M2-DSN-A",
    "team": "DSN",
    "phase": "M2",
    "title": "후기 요청 실행 결과 점검 및 스크립트 보완",
    "category": "구매후기",
    "week": 4,
    "planNote": "",
    "sortOrder": 111
  },
  {
    "id": "M2-VID-1",
    "team": "VID",
    "phase": "M2",
    "title": "촬영 D-5 체크리스트 갑 서면 확인",
    "category": "촬영 사전 확정",
    "week": 1,
    "planNote": "D-5 서면 확인 · 미확인 시 촬영 연기 사유",
    "sortOrder": 112
  },
  {
    "id": "M2-VID-2",
    "team": "VID",
    "phase": "M2",
    "title": "촬영 1회 실행 (8시간)",
    "category": "촬영",
    "week": 2,
    "planNote": "",
    "sortOrder": 113
  },
  {
    "id": "M2-VID-3",
    "team": "VID",
    "phase": "M2",
    "title": "유튜브 롱폼 2편 제작·게시",
    "category": "월 정량 산출물",
    "week": 4,
    "planNote": "별첨3 · 제20조① 수량 미달 시 이월 또는 환산단가 차감",
    "sortOrder": 114
  },
  {
    "id": "M2-VID-4",
    "team": "VID",
    "phase": "M2",
    "title": "유튜브 숏폼 10편 제작·게시 (릴스 크로스 배포)",
    "category": "월 정량 산출물",
    "week": 4,
    "planNote": "별첨3 · 제20조① 수량 미달 시 이월 또는 환산단가 차감",
    "sortOrder": 115
  },
  {
    "id": "M2-VID-5",
    "team": "VID",
    "phase": "M2",
    "title": "익월분 선행 제작 버퍼 확보",
    "category": "선행 제작",
    "week": 4,
    "planNote": "",
    "sortOrder": 116
  },
  {
    "id": "M3-MKT-1",
    "team": "MKT",
    "phase": "M3",
    "title": "콘텐츠 캘린더 제안 및 갑 승인 수령",
    "category": "콘텐츠 캘린더",
    "week": 1,
    "planNote": "",
    "sortOrder": 117
  },
  {
    "id": "M3-MKT-2",
    "team": "MKT",
    "phase": "M3",
    "title": "네이버 블로그 4건 발행 (주제축 고정)",
    "category": "월 정량 산출물",
    "week": 4,
    "planNote": "별첨3 · 제20조① 수량 미달 시 이월 또는 환산단가 차감",
    "sortOrder": 118
  },
  {
    "id": "M3-MKT-3",
    "team": "MKT",
    "phase": "M3",
    "title": "스마트스토어 콘텐츠 3건",
    "category": "네이버 채널",
    "week": 2,
    "planNote": "",
    "sortOrder": 119
  },
  {
    "id": "M3-MKT-4",
    "team": "MKT",
    "phase": "M3",
    "title": "스마트플레이스 갱신 — 남양주 중심",
    "category": "네이버 채널",
    "week": 2,
    "planNote": "",
    "sortOrder": 120
  },
  {
    "id": "M3-MKT-5",
    "team": "MKT",
    "phase": "M3",
    "title": "자사몰 상품 등록·수정 3건",
    "category": "자사몰 운영",
    "week": 4,
    "planNote": "",
    "sortOrder": 121
  },
  {
    "id": "M3-MKT-6",
    "team": "MKT",
    "phase": "M3",
    "title": "광고 주간 최적화 4주 (키워드·입찰·소재·전환 동선)",
    "category": "광고 최적화",
    "week": 4,
    "planNote": "",
    "sortOrder": 122
  },
  {
    "id": "M3-MKT-7",
    "team": "MKT",
    "phase": "M3",
    "title": "댓글·DM 1차 응대 (영업일 24시간 내)",
    "category": "채널 운영",
    "week": 4,
    "planNote": "",
    "sortOrder": 123
  },
  {
    "id": "M3-MKT-8",
    "team": "MKT",
    "phase": "M3",
    "title": "광고 매체별 실집행 증빙 수집",
    "category": "광고 증빙",
    "week": 4,
    "planNote": "제11조③ 집행 증빙 첨부 의무 · 무단 집행 즉시 해지",
    "sortOrder": 124
  },
  {
    "id": "M3-MKT-9",
    "team": "MKT",
    "phase": "M3",
    "title": "주간 브리핑 4회 발송 (한 일·집행·지표·계획)",
    "category": "주간 브리핑",
    "week": 4,
    "planNote": "제30조④ 보고 의무 불이행 시 해지 사유",
    "sortOrder": 125
  },
  {
    "id": "M3-MKT-10",
    "team": "MKT",
    "phase": "M3",
    "title": "상담 시트 유입 경로 집계 및 리포트 반영",
    "category": "상담 데이터",
    "week": 4,
    "planNote": "",
    "sortOrder": 126
  },
  {
    "id": "M3-MKT-11",
    "team": "MKT",
    "phase": "M3",
    "title": "브랜드·지역 검색 순위 점검",
    "category": "브랜드 검색",
    "week": 3,
    "planNote": "",
    "sortOrder": 127
  },
  {
    "id": "M3-MKT-12",
    "team": "MKT",
    "phase": "M3",
    "title": "지원사업 트랙 캘린더·증빙자산 매핑 갱신",
    "category": "지원사업",
    "week": 3,
    "planNote": "",
    "sortOrder": 128
  },
  {
    "id": "M3-MKT-13",
    "team": "MKT",
    "phase": "M3",
    "title": "월간 성과보고서 제출 (익월 5영업일 이내)",
    "category": "월간 보고",
    "week": 5,
    "planNote": "제19조⑧ 보고서 미제출 시 대금 지급 보류",
    "sortOrder": 129
  },
  {
    "id": "M3-MKT-14",
    "team": "MKT",
    "phase": "M3",
    "title": "성과 검토회의 30분 이상 실시",
    "category": "검토회의",
    "week": 5,
    "planNote": "월 1회 30분 이상 실시 의무",
    "sortOrder": 130
  },
  {
    "id": "M3-MKT-A",
    "team": "MKT",
    "phase": "M3",
    "title": "경쟁 3사 검색 순위·후기 수 월간 추적 및 리포트 반영",
    "category": "경쟁 모니터링",
    "week": 3,
    "planNote": "",
    "sortOrder": 131
  },
  {
    "id": "M3-MKT-B",
    "team": "MKT",
    "phase": "M3",
    "title": "쇼룸 주간 응대 캐파 대비 예약 분산 점검",
    "category": "쇼룸 예약 동선",
    "week": 4,
    "planNote": "",
    "sortOrder": 132
  },
  {
    "id": "M3-DSN-1",
    "team": "DSN",
    "phase": "M3",
    "title": "인스타그램 피드 10건 (카드뉴스 포함)",
    "category": "월 정량 산출물",
    "week": 4,
    "planNote": "별첨3 · 제20조① 수량 미달 시 이월 또는 환산단가 차감",
    "sortOrder": 133
  },
  {
    "id": "M3-DSN-2",
    "team": "DSN",
    "phase": "M3",
    "title": "기획전·프로모션 배너 1건",
    "category": "자사몰 운영",
    "week": 4,
    "planNote": "",
    "sortOrder": 134
  },
  {
    "id": "M3-DSN-3",
    "team": "DSN",
    "phase": "M3",
    "title": "유튜브 롱폼 썸네일 2종",
    "category": "촬영",
    "week": 2,
    "planNote": "",
    "sortOrder": 135
  },
  {
    "id": "M3-DSN-4",
    "team": "DSN",
    "phase": "M3",
    "title": "상품 상세 이미지 갱신·보완",
    "category": "자사몰 운영",
    "week": 4,
    "planNote": "",
    "sortOrder": 136
  },
  {
    "id": "M3-DSN-5",
    "team": "DSN",
    "phase": "M3",
    "title": "후기 요청 발송물 제작·갱신",
    "category": "구매후기",
    "week": 4,
    "planNote": "",
    "sortOrder": 137
  },
  {
    "id": "M3-DSN-6",
    "team": "DSN",
    "phase": "M3",
    "title": "자사몰 경미 수정 (월 3시간 이내 관리)",
    "category": "자사몰 수정",
    "week": 4,
    "planNote": "",
    "sortOrder": 138
  },
  {
    "id": "M3-DSN-A",
    "team": "DSN",
    "phase": "M3",
    "title": "후기 요청 실행 결과 점검 및 스크립트 보완",
    "category": "구매후기",
    "week": 4,
    "planNote": "",
    "sortOrder": 139
  },
  {
    "id": "M3-VID-1",
    "team": "VID",
    "phase": "M3",
    "title": "촬영 D-5 체크리스트 갑 서면 확인",
    "category": "촬영 사전 확정",
    "week": 1,
    "planNote": "D-5 서면 확인 · 미확인 시 촬영 연기 사유",
    "sortOrder": 140
  },
  {
    "id": "M3-VID-2",
    "team": "VID",
    "phase": "M3",
    "title": "촬영 1회 실행 (8시간)",
    "category": "촬영",
    "week": 2,
    "planNote": "",
    "sortOrder": 141
  },
  {
    "id": "M3-VID-3",
    "team": "VID",
    "phase": "M3",
    "title": "유튜브 롱폼 2편 제작·게시",
    "category": "월 정량 산출물",
    "week": 4,
    "planNote": "별첨3 · 제20조① 수량 미달 시 이월 또는 환산단가 차감",
    "sortOrder": 142
  },
  {
    "id": "M3-VID-4",
    "team": "VID",
    "phase": "M3",
    "title": "유튜브 숏폼 10편 제작·게시 (릴스 크로스 배포)",
    "category": "월 정량 산출물",
    "week": 4,
    "planNote": "별첨3 · 제20조① 수량 미달 시 이월 또는 환산단가 차감",
    "sortOrder": 143
  },
  {
    "id": "M3-VID-5",
    "team": "VID",
    "phase": "M3",
    "title": "익월분 선행 제작 버퍼 확보",
    "category": "선행 제작",
    "week": 4,
    "planNote": "",
    "sortOrder": 144
  }
];
